project:
  type: website

website:
  title: "Scott Milner — Pipeline TD / Software Dev"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/scottdmilner
      - icon: linkedin
        href: https://linkedin.com/in/sdmilner
  open-graph:
    locale: en_US
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto
